# Generated by Django 5.1.3 on 2024-11-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManager', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва постачальника')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактна особа')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адреса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва складу')),
                ('location', models.TextField(verbose_name='Розташування')),
                ('manager', models.CharField(blank=True, max_length=200, null=True, verbose_name='Менеджер складу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
            },
        ),
    ]
