# Generated by Django 5.1.3 on 2024-11-20 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код купону')),
                ('valid_from', models.DateTimeField(verbose_name='Дійсний з')),
                ('valid_to', models.DateTimeField(verbose_name='Дійсний до')),
                ('active', models.BooleanField(default=True, verbose_name='Активний')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ліміт використань')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купони',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Метод доставки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість доставки')),
                ('estimated_time', models.CharField(max_length=50, verbose_name='Орієнтовний час доставки')),
            ],
            options={
                'verbose_name': 'Метод доставки',
                'verbose_name_plural': 'Методи доставки',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва знижки')),
                ('discount_type', models.CharField(choices=[('percentage', 'Відсоток'), ('fixed', 'Фіксована сума')], max_length=50, verbose_name='Тип знижки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значення знижки')),
                ('start_date', models.DateTimeField(verbose_name='Початок дії')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Кінець дії')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Знижка',
                'verbose_name_plural': 'Знижки',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderManager.coupon', verbose_name='Купон'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderManager.deliverymethod', verbose_name='Метод доставки'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManager.discount', verbose_name='Знижка'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderManager.discount', verbose_name='Знижка'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Метод оплати')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікується'), ('completed', 'Завершено'), ('failed', 'Не вдалося')], default='pending', max_length=20, verbose_name='Статус оплати')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплати')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакції')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OrderManager.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплати',
            },
        ),
    ]
